Select 
	al1.idRequerimiento,
	al1.fechaInicio,
	al1.fechaEsperada,
	al1.fechaFin,
	case 
		when al1.estado = 1 and al1.fechaEsperada <= now() then 3
		when al1.estado = 1 and al1.fechaEsperada > now() then 1
	else
		al1.estado
	end estado,
	al2.actividad,
	al3.rol
FROM 
	elx_rep_estados al1,
	elx_wf_actividad al2,
	elx_hr_rol al3
WHERE
	al1.idActividad = al2.idActividad and
	al2.idRol = al3.idRol 

